<?php

/**
 * @file module file for tbtrack_charts
 */

function tbtrack_charts_tbtrack_ranking_product_report_platform($product, $platform) {
  // build yourself array for rander

  // Daily average of product ranking
  $output['charts']['daily'] = array(
    '#theme' => 'chart',
    '#title' => t('Daily average of product ranking'),
    '#chart_id' => 'daily-arerage-ranking',
    '#type' => CHART_TYPE_LINE,
    '#data' => array(
      'a' => array(1,2,3,12,23,241,1),
      'b' => array(1,3,32,12,34,122,5),
    ),
  );
  return $output;
}