<?php

/**
 * @file
 * define tmall platform info and implements selector callback
 */

function tbtrack_tmall_tbtrack_platform_info() {
  return array(
    'tmall' => array(
      'title' => 'TMall',
      // Specify a field used to store the product ID of the platform
      'field' => 'tbtrack_tmall_product_id',
      'ranking' => array(
        'search host' => 'http://list.tmall.com',
        'search path' => '/search_dispatcher.htm',
        'charset' => 'GBK',
        'page size' => 60,
        'selector callback' => '_tbtrack_tmall_selector',
        'selector formula' => '#J_ItemList div.product',
      ),
    ),
  );
}

/**
 * The selector for tmall that to determine whether the elements matched
 */
function _tbtrack_tmall_selector($e, $product_id) {
  $property = 'data-id';
  if ($e->{$property} == $product_id) {
    return $e;
  }
  return FALSE;
}